### PR TITLE
Make sure b2 exits immediately on syntax errors

### LINKED ISSUE #539: BoostBuild.Tester not capturing b2 status correctly for -fx
After submission of the #538, `b2` fix to correctly report `1` instead of `0` for Jam syntax errors, I realised something is still fishy.

1. Why none of the tests addressing syntax errors did not require any changes after the fix?
2. Better, why those tests which actually expected `status=1` had been passing at all, for long time?

------

There are two common ways of how tests generate Jam scripts and the `BoostBuild.Tester` invokes `b2` for them:

1. https://github.com/boostorg/build/blob/f951fb15596f0865f58adffc183ed5de9defd100/test/exit_status.py#L13-L24
2. https://github.com/boostorg/build/blob/f951fb15596f0865f58adffc183ed5de9defd100/test/core_source_line_tracking.py#L39-L44

To paraphrase my question No 2 above: why the `core_source_line_tracking.py` had been reporting `PASSED` without the #538 fix?

------

So, I translated both types of test cases from Python to plain `b2` command line (as `BoostBuild.Tester` generates them) and passed a Jam script with broken syntax.

Then, I used `b2` build **without** the #538 fix:

1. ```shell
    mloskot@bionic:with-jamroot$ pwd
    /mnt/d/boost.wsl/tools/build/test/with-jamroot

    mloskot@bionic:with-jamroot$ cat jamroot.jam
    exe h : h.cpp

    mloskot@bionic:with-jamroot$ /mnt/d/boost.wsl/tools/build/test/../src/engine/b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc --test-config="/mnt/d/boost.wsl/tools/build/test/test-config.jam"
    jamroot.jam:1: syntax error at EOF
    ...found 1 target...

    mloskot@bionic:with-jamroot$ echo $?
    0
    ```


2. ```shell
    mloskot@bionic:with-file$ pwd
    /mnt/d/boost.wsl/tools/build/test/with-file

    mloskot@bionic:with-file$ cat file.jam
    exe h : h.cpp

    mloskot@bionic:with-file$ /mnt/d/boost.wsl/tools/build/test/../src/engine/b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc --test-config="/mnt/d/boost.wsl/tools/build/test/test-config.jam" -ffile.jam
    file.jam:1: syntax error at EOF
    don't know how to make toolset=gcc
    ...found 1 target...
    ...can't find 1 target...

    mloskot@bionic:with-file$ echo $?
    1
    ```

Critical here is the difference in the `b2` outputs, that is, for the `b2 -ffile.jam` case, there seem to be actually two outputs bundled in one:

```
file.jam:1: syntax error at EOF
```

which presumably reported status `0` - remember, the #538 fix is not there - and this

```
...found 1 target...
...can't find 1 target...
```

which overrides the `status=0` with `status=1` and makes `BoostBuild.Tester` all happy to report `PASSED` as it expects `status=1`

```python
t.run_build_system(["-ffile.jam"], status=1)
```

Poor `BoostBuild.Tester` is not aware it is being cheated :)

------

To prove my theory that the tests runner is actually not *seeing* the results it thinks it does, I created new test `/mnt/d/boost.wsl/tools/build/test/core_syntax_error_exit_status.py`, modified the tests list in the `test_all.py` to run only test scripts of my interest, and I run equivalents of the two cases above:

1. `b2` with `-ffile.jam` case

    ```shell
    $ cat core_syntax_error_exit_status.py
    #!/usr/bin/python
    import BoostBuild
    t = BoostBuild.Tester()
    t.write("file.jam", """
    exe hello : hello.cpp

    """)
    t.run_build_system(["-ffile.jam"], status=1)
    t.cleanup()

    $ python test_all.py gcc
    core_source_line_tracking     :PASSED
    core_syntax_error_exit_status :PASSED

            === Test summary ===
            PASS: 2
            FAIL: 0
    ```

2. `b2` with (implicit) `jamroot.jam`

    ```shell
    $ cat core_syntax_error_exit_status.py
    #!/usr/bin/python
    import BoostBuild
    t = BoostBuild.Tester()
    t.write("jamroot.jam", """
    exe hello : hello.cpp

    """)
    t.run_build_system(status=1)
    t.cleanup()

    $ python test_all.py gcc
    core_source_line_tracking     :PASSED
    core_syntax_error_exit_status :FAILED
    failure {{{
    "['/mnt/d/boost.wsl/tools/build/test/../src/engine/b2', '-sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.."', '-j1', 'toolset=gcc', '--test-config="/mnt/d/boost.wsl/tools/build/test/test-config.jam"']" returned 0 (expected 1)
    }}}
    reason {{{
    unexpected status returned by bjam
    }}}
    changes caused by the last build command {{{
    Added files   : ['bin/config.log', 'bin/project-cache.jam']
    Removed files : []
    Modified files: []
    Touched files : []

    }}}
    STDOUT {{{
    ...found 1 target...

    }}}
    STDERR {{{

    }}}
    stacktrace {{{
    at line 608 of /mnt/d/boost.wsl/tools/build/test/BoostBuild.py (fail_test)
            from line 497 of /mnt/d/boost.wsl/tools/build/test/BoostBuild.py (run_build_system)
            from line 8 of /mnt/d/boost.wsl/tools/build/test/core_syntax_error_exit_status.py (<module>)
            from line 62 of test_all.py (run_tests)
            from line 170 of test_all.py (<module>)

    }}}

            === Test summary ===
            PASS: 1
            FAIL: 1
    ```

    Finally, with the #538 fix, 

    ```shell
    $ python test_all.py gcc
    core_syntax_error_exit_status :PASSED
    core_source_line_tracking     :PASSED

            === Test summary ===
            PASS: 2
            FAIL: 0
    ```

To summarise, the `status` **aliasing** in case of the `-ffile.jam` invocation kept the bug uncovered.

It seems worth to add the `core_source_line_tracking.py` script to the tests suite.

### PR DESCRIPTION
**Pull request by mloskot**
Refines #538

Fixes #539

------

There is a difference between BEFORE/AFTER outputs of `b2` for syntactically erroneous files.
Although I don't understand some of parts of the BEFORE outputs (see questions below), the AFTER output is now shorter and clearer, I think.

### Situation BEFORE this fix:

1. Valid `jamroot.jam`

    ```
    $ cat jamroot.jam
    exe foo : foo.cpp ;

    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc
    ...found 7 targets...
    ...updating 5 targets...
    gcc.compile.c++ bin/gcc-9/debug/foo.o
    gcc.link bin/gcc-9/debug/foo
    ...updated 5 targets...

    $ echo $?
    0
    ```

1. Invalid `jamroot.jam`

    ```
    $ cat jamroot.jam
    exe foo : foo.cpp

    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc
    jamroot.jam:1: syntax error at EOF
    bin/project-cache.jam:4: syntax error at keyword {
    ...found 1 target...

    $ echo $?
    1
    ```

    What is this `bin/project-cache.jam:4: syntax error at keyword {` in the output?

1. Invalid `file.jam`

    ```
    $ cat file.jam
    exe foo : foo.cpp

    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 -ffile.jam toolset=gcc
    file.jam:1: syntax error at EOF
    don't know how to make toolset=gcc
    ...found 1 target...
    ...can't find 1 target...

    $ echo $?
    1
    ```

    What is this `don't know how to make toolset=gcc` in the output?

### Situation AFTER this fix:

2. Valid `jamroot.jam`

    ```
    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc
    a
    ...found 7 targets...
    ...updating 5 targets...
    gcc.compile.c++ bin/gcc-9/debug/foo.o
    gcc.link bin/gcc-9/debug/foo
    ...updated 5 targets...

    $ echo $?
    0
    ```

2. Invalid `jamroot.jam`

    ```
    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc
    jamroot.jam:1: syntax error at EOF
    ...found 1 target...

    $ echo $?
    1
    ```

2. Invalid `file.jam`

    ```
    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build/test/.." -j1 toolset=gcc -ffile.jam
    file.jam:1: syntax error at EOF

    $ echo $?
    1
    ```

### CODE REVIEW

File: src/engine/jam.cpp [hunk 1]
```diff
@@ -649,9 +649,14 @@ int main( int argc, char * * argv, char * * arg_environ )
...
+        /* FIXME: What shall we do if builtin_update_now,
+         * the sole place setting last_update_now_status,
+         * failed earlier?
+         */
+
         status = yyanyerrors();
-        if ( status && !last_update_now_status )
-            last_update_now_status = status;
+        if ( status )
+            goto cleanup;
```
Comment (grafikrobot) [inline src/engine/jam.cpp]: Not fond of `goto` in general. And in this case using it has the effect of skipping over the `PROFILE_EXIT` and `profile_dump`. I'd prefer wrapping the code below it, up to the `PROFILE_EXIT`, with an `if (!status)`.

Comment (mloskot) [reply src/engine/jam.cpp]: I was hoping for my first ever `goto` contribution to a production code ;)
I noticed `goto` users in the current code and I followed the pattern. I did miss the skipped `PROFILE_EXIT` though.

I will change that.

**Comment by mloskot** [comment]
@grafikrobot I have submitted new commit with the refinement of the change.

But, I've noticed something strange which I need help in clarifying:

- `b2` reports syntax errors to `stdout` and not `stderr`, is this by design?
- `b2` run for the "Invalid jamroot.jam" test case no longer outputs `jamroot.jam:1: syntax error at EOF` but if I run `-ffile.jam`, the error is printed. This is puzzling the most!

Here is the re-run of the **Situation AFTER this fix** from the PR description above but with `XXX` extra output I added inside `if ( status )` case and inside the `cleanup` function to trace it 

1. Valid `jamroot.jam`

    ```
    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build" -j1 toolset=gcc >out.txt 2>err.txt

    $ cat out.txt
    ...found 7 targets...
    ...updating 5 targets...
    gcc.compile.c++ bin/gcc-9/debug/foo.o
    gcc.link bin/gcc-9/debug/foo
    ...updated 5 targets...

    $ cat err.txt
    XXX cleanup
    ```

2. Invalid `jamroot.jam`

    ```
    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build" -j1 toolset=gcc >out.txt 2>err.txt

    $ cat out.txt
    ...found 1 target...

    $ cat err.txt
    XXX aborting yyanyerrors status=1
    XXX cleanup
    ```

    Why no syntax error printed here for `jamroot.jam` but it is printed for `file.jam` below?

    Both files have the same invalid content `exe foo : foo.cpp` w/o ` ;` terminator.

3. Invalid `file.jam`

    ```
    $ b2 -sBOOST_BUILD_PATH="/mnt/d/boost.wsl/tools/build" -j1 -ffile.jam toolset=gcc >out.txt 2>err.txt

    $ cat out.txt
    file.jam:1: syntax error at EOF

    $ cat err.txt
    XXX aborting yyanyerrors status=1
    XXX cleanup
    ```

What is going on?

**Comment by mloskot** [comment]
@grafikrobot No exciting reason, I suspected we will need to call the cleanup from more places. I have replaced the function with the branch.
